name: EQC-Server CICD

on:
  push:
    branches:
      - master

jobs:
  Build:
    runs-on: ubuntu-latest
    services:
      registry:
        image: registry:2
        ports:
          - 5000:5000
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: Set up JDK & Maven
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '8'
          cache: maven
      - name: Build Jar
        run: mvn clean package -DskipTests=true -P prod,!dev

      - name: Set up Docker QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          driver-opts: network=1panel

      - name: Docker Build push
        uses: docker/build-push-action@v6
        with:
          context: ./admin
          push: true
          tags: localhost:5000/eqc-server:latest
